[package]
name = "lucario_os"
version = "0.0.1"
edition = "2021"

[profile.dev]
panic = "abort"
overflow-checks = false

[profile.release]
panic = "abort"
overflow-checks = false

[dependencies]
lazy_static = { version = "1.4.0", features = ["spin_no_std"] }
