name: Autobuild

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Step 1 - Software installation
        run: |
          sudo apt install build-essential curl xorriso grub-pc-bin mtools llvm lld fasm zip

      - name: Step 1.1 - Rustup.rs
        run: |
          curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain nightly -y

      - name: Step 2 - Compiling the kernel
        run: make

      - name: Step 3 - ISO assembly
        run: make iso

      - name: Step 4 - File Existance Check
        run: |
          ls isodir/*

      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./LucarioOS.iso
          asset_name: LucarioOS.iso
          asset_content_type: application/octetstream
